ControlDeClientes/ControlDeClientes/Controllers/ClientsController.cs
using ControlDeClientes.Helpers;
using ControlDeClientes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlDeClientes.Controllers
{
    public class ClientsController : Controller
    {
        // GET: Clients
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to Client Control Stage";
            return View(Storage.Instance.ClientsList);
        }

        // GET: Clients/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            ViewBag.Message = "Welcome to Create Stage";
            return View();
        }

       

        // POST: Clients/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var Client = new ClientsModel
                {
                    Name = collection["name"],
                    LastName = collection["LastName"],
                    Phone = int.Parse(collection["Phone"]),
                    Description = collection["Description"]
                };

                if (Client.Save())
                {
                    return RedirectToAction("Index");
                }else
                {
                    return View(Client);
                }
            }
            catch
            {
                return View();
            }
        }

       

        // GET: Clients/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Clients/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Clients/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ControlDeClientes/ControlDeClientes/Controllers/FilterController.cs
using System;
using System.Collections.Generic;
using ControlDeClientes.Models;
using ControlDeClientes.Helpers;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlDeClientes.Controllers
{
    public class FilterController : Controller
    {
        // GET: Filter
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SortName()
        {
            return View(Storage.Instance.ClientsSortedByName);
        }

        public ActionResult SortLastName()
        {
            return View(Storage.Instance.ClientsSortedByLastName);
        }

        // GET: Filter/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Filter/Create
        public ActionResult Create()
        {
            return View();
        }



        // POST: Filter/Create
        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            try
            {
                var FilterData = new FilterModel
                {
                    TypeSort = collection["TypeSort"]
                };

                if (FilterData.Save())
                {
                    string TypeOfSort = Storage.Instance.Type;

                    switch (TypeOfSort)
                    {
                        case "SortName":
                            var AnonymousClient = new ClientsModel();
                                if (AnonymousClient.SortName())
                                {
                                    return RedirectToAction("SortName");
                                }
                        break;

                        case "SortLastName":
                            var AnonymousSecondClient = new ClientsModel();
                            if (AnonymousSecondClient.SortLastName())
                            {
                                return RedirectToAction("SortLastName");
                            }

                        break;
                    }
                }
                
              
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Filter/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Filter/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Filter/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Filter/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ControlDeClientes/ControlDeClientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr") 
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        @Html.ActionLink("Laboratorio 0", "Index", "Clients", new object { }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                @Html.ActionLink("Clients Control", "Index", "Clients", new object { }, new { @class = "nav-link" })
                @Html.ActionLink("Clients Filter", "Index", "Filter", new object { }, new { @class = "nav-link" })
            </ul>
        </div>
    </nav>
   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>